#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'arrayManipulation' function below.
#
# The function is expected to return a LONG_INTEGER.
# The function accepts following parameters:
#  1. INTEGER n
#  2. 2D_INTEGER_ARRAY queries
#

def arrayManipulation(n, queries):
    # Write your code here
    maxi = 0
    for query in queries:
        maxi = max(maxi,query[1])
    arr = [0 for _ in range(maxi+3)]
    for query in queries:
        arr[query[0]]+=query[2]
        if query[1]+1 < len(arr):
            arr[query[1]+1] -= query[2]
    
    for each in range(1,len(arr)):
        arr[each] += arr[each - 1]
    
    maxi = float("-inf")
    
    for each in range(len(arr)):
        maxi = max(maxi, arr[each])
    
    return maxi
    
    
    
    
    
    
    
    
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    m = int(first_multiple_input[1])

    queries = []

    for _ in range(m):
        queries.append(list(map(int, input().rstrip().split())))

    result = arrayManipulation(n, queries)

    fptr.write(str(result) + '\n')

    fptr.close()
